name: unpub
description: Self-hosted private Dart Pub server for Enterprise, with a simple web interface to search and view packages information.
version: 2.0.0
homepage: https://github.com/bytedance/unpub
environment:
  sdk: ">=2.18.0 <3.0.0"
executables:
  unpub: unpub
dependencies:
  args: ^2.3.1
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  http_parser: ^4.0.2
  http: ^0.13.5
  archive: ^3.3.2
  logging: ^1.1.0
  meta: ^1.8.0
  googleapis: ^9.2.0
  yaml: ^3.1.1
  pub_semver: ^2.1.2
  json_annotation: ^4.7.0
  mongo_dart: ^0.8.0
  mime: ^1.0.2
  intl: ^0.17.0
  path: ^1.8.2
  collection: ^1.17.0
  shelf_cors_headers: ^0.1.4
  shelf_multipart: ^1.0.0
dev_dependencies:
  test: ^1.22.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  shelf_router_generator: ^1.0.4
  chunked_stream: ^1.4.1
