name: unpub
description: Self-hosted private Dart Pub server for Enterprise, with a simple web interface to search and view packages information.
version: 2.0.0
homepage: https://github.com/bytedance/unpub
environment:
  sdk: ">=2.12.0 <3.0.0"
executables:
  unpub: unpub
dependencies:
  args: ^2.3.0
  shelf: ^1.2.0
  shelf_router: ^1.1.2
  http_parser: ^4.0.0
  http: ^0.13.4
  archive: ^3.2.1
  logging: ^1.0.2
  meta: ^1.7.0
  googleapis: ^8.0.0
  yaml: ^3.1.0
  pub_semver: ^2.1.0
  json_annotation: ^4.4.0
  mongo_dart: ^0.7.4
  mime: ^1.0.1
  intl: ^0.17.0
  path: ^1.8.1
  collection: ^1.15.0
  shelf_cors_headers: ^0.1.2
  shelf_multipart: ^1.0.0
dev_dependencies:
  test: ^1.20.1
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  shelf_router_generator: ^1.0.2
  chunked_stream: ^1.4.1
